export default [
    {id: 1, menuName: "系统设置", menuUrl: "/sys", menuCmd: "Main", menuIcon: "el-icon-menu", parentId: 0, menuLevel: 1, menuIndex: 1},
    {id: 101, menuName: "权限管理", menuUrl: "/sys/roleList", menuCmd: "sys/RoleList", menuIcon: "el-icon-menu", parentId: 1, menuLevel: 2, menuIndex: 1},
    {id: 102, menuName: "医院科室管理", menuUrl: "/sys/deptList", menuCmd: "sys/DeptList", menuIcon: "el-icon-menu", parentId: 1, menuLevel: 2, menuIndex: 2},
    {id: 103, menuName: "用户管理", menuUrl: "/sys/userList", menuCmd: "sys/UserList", menuIcon: "el-icon-menu", parentId: 1, menuLevel: 2, menuIndex: 3},
    {id: 111, menuName: "病症标签", menuUrl: "/base/diseaseLabelList", menuCmd: "base/DiseaseLabelList", menuIcon: "el-icon-menu", parentId: 1, menuLevel: 2, menuIndex: 4},
    {id: 107, menuName: "疾病字典", menuUrl: "/base/dicDisease", menuCmd: "base/DicDisease", menuIcon: "el-icon-menu", parentId: 1, menuLevel: 2, menuIndex: 8},
    {id: 106, menuName: "回访模板", menuUrl: "/base/templateReturnList", menuCmd: "base/TemplateReturnList", menuIcon: "el-icon-menu", parentId: 1, menuLevel: 2, menuIndex: 6},
    {id: 109, menuName: "健康建议字典", menuUrl: "/base/dicHealthAdvice", menuCmd: "Main", menuIcon: "el-icon-menu", parentId: 1, menuLevel: 2, menuIndex: 10},
    {id: 104, menuName: "修改密码", menuUrl: "/sys/updatePassword", menuCmd: "sys/UpdatePassword", menuIcon: "el-icon-menu", parentId: 1, menuLevel: 2, menuIndex: 99},
    {id: 4, menuName: "信息采集", menuUrl: "/messInput", menuCmd: "Main", menuIcon: "el-icon-menu", parentId: 0, menuLevel: 1, menuIndex: 4},
    {id: 403, menuName: "入院记录", menuUrl: "/messInput/inputSalesman", menuCmd: "messInput/InputSalesman", menuIcon: "el-icon-menu", parentId: 4, menuLevel: 2, menuIndex: 3},
    {id: 603, menuName: "门诊记录", menuUrl: "/return/appointmentClinic", menuCmd: "return/AppointmentClinic", menuIcon: "el-icon-menu", parentId: 4, menuLevel: 2, menuIndex: 4},
    {id: 404, menuName: "患者基础信息", menuUrl: "/patients/patientsMess", menuCmd: "patients/PatientsMess", menuIcon: "el-icon-menu", parentId: 4, menuLevel: 2, menuIndex: 5},
    {id: 6, menuName: "患者回访", menuUrl: "/access", menuCmd: "Main", menuIcon: "el-icon-menu", parentId: 0, menuLevel: 1, menuIndex: 6},
    {id: 601, menuName: "患者回访", menuUrl: "/return/doAccess", menuCmd: "return/DoAccess", menuIcon: "el-icon-menu", parentId: 6, menuLevel: 2, menuIndex: 1},
    {id: 602, menuName: "回访记录", menuUrl: "/return/accessList", menuCmd: "return/AccessList", menuIcon: "el-icon-menu", parentId: 6, menuLevel: 2, menuIndex: 2},
    {id: 7, menuName: "查询统计", menuUrl: "/analyse", menuCmd: "Main", menuIcon: "el-icon-menu", parentId: 0, menuLevel: 1, menuIndex: 7},
    {id: 701, menuName: "患者医疗记录", menuUrl: "/analyse/medicalRecordList", menuCmd: "analyse/MedicalRecordList", menuIcon: "el-icon-menu", parentId: 7, menuLevel: 2, menuIndex: 1},
    {id: 702, menuName: "患者回访情况分析", menuUrl: "/analyse/accessAnalyse", menuCmd: "analyse/AccessAnalyse", menuIcon: "el-icon-menu", parentId: 7, menuLevel: 2, menuIndex: 2},
    {id: 703, menuName: "推文阅读情况分析", menuUrl: "/analyse/tweetAnalyse", menuCmd: "analyse/TweetAnalyse", menuIcon: "el-icon-menu", parentId: 7, menuLevel: 2, menuIndex: 3},
]
