// 回访模板数据
export default [
    {id: 1, showIndex: 1, returnItem: "姓名", candidateValue: "#patientName", state: 1, type: 1},
    {id: 2, showIndex: 2, returnItem: "性别", candidateValue: "#patientSex", state: 1, type: 1},
    {id: 3, showIndex: 3, returnItem: "身份证号", candidateValue: "#patientCardNo", state: 1, type: 1},
    {id: 4, showIndex: 4, returnItem: "入诊医院", candidateValue: "#hospitalName", state: 1, type: 1},
    {id: 5, showIndex: 5, returnItem: "主治医生", candidateValue: "#DoctorName", state: 1, type: 1},
    {id: 6, showIndex: 6, returnItem: "患者是否有疼痛", candidateValue: "是|否", state: 1, type: 2},
    {id: 7, showIndex: 7, returnItem: "每日出现爆发痛次数", candidateValue: "0|1|2|3|4|5|5次以上", state: 1, type: 2},
    {id: 8, showIndex: 8, returnItem: "疼痛性质", candidateValue: "酸痛|胀痛|麻刺痛|刺痛|痉挛痛|烧灼样痛|钝痛|搏动性疼痛|电击样痛|压迫性痛|刀割样痛|其他|无", state: 1, type: 2},
    {id: 9, showIndex: 9, returnItem: "使疼痛加重的因素", candidateValue: "活动|体位变动|进食|咳嗽|情绪激动|排便|其他|无", state: 1, type: 2},
    {id: 10, showIndex: 10, returnItem: "患者现在的疼痛大多数是几分", candidateValue: "0|1|2|3|4|5|6|7|8|9|10", state: 1, type: 2},
    {id: 11, showIndex: 11, returnItem: "患者睡眠状态", candidateValue: "良好|一般|差", state: 1, type: 2},
    {id: 12, showIndex: 12, returnItem: "患者饮食状态", candidateValue: "良好|一般|差", state: 1, type: 2},
    {id: 13, showIndex: 13, returnItem: "患者精神状态", candidateValue: "良好|一般|差", state: 1, type: 2},
    {id: 14, showIndex: 14, returnItem: "患者用药后的不良反应", candidateValue: "便秘|恶心|呕吐|昏睡|谵妄|头晕|尿潴留|皮肤瘙痒|其他|无", state: 1, type: 2},
    {id: 15, showIndex: 15, returnItem: "患者的止疼药物还可以服用几天", candidateValue: "0|1|2|3|4|5|6|7|7天以上", state: 1, type: 2},
    {id: 16, showIndex: 16, returnItem: "患者是否需要医生指导", candidateValue: "是|否", state: 1, type: 2},
    {id: 17, showIndex: 17, returnItem: "患者是否需要医生指导1", candidateValue: "是|否", state: 2, type: 2},
    {id: 18, showIndex: 18, returnItem: "患者是否需要医生指导2", candidateValue: "是|否", state: 2, type: 2},
    {id: 19, showIndex: 19, returnItem: "其他情况", candidateValue: "", state: 1, type: 2},
    {id: 50, showIndex: 1, returnItem: "疼痛评分", candidateValue: "0|1|2|3|4|5|6|7|8|9|10", state: 1, type: 5},
    {id: 51, showIndex: 2, returnItem: "医嘱", candidateValue: "", state: 1, type: 5},
    {id: 52, showIndex: 3, returnItem: "预约门诊", candidateValue: "", state: 1, type: 5, component:"date"},
    {id: 53, showIndex: 4, returnItem: "健康建议", candidateValue: "", state: 1, type: 6},
]